### ISSUE TITLE
Phylogeographic diffusion in discrete space

### ISSUE THREAD

**Issue by Spatial-R** [ropensci/beautier#120]
Hello, thanks for your nice package.  Can i use the beauties to estimate the phylogeographic diffusion in discrete space? Is there any example?

**Comment by richelbilderbeek** [comment]
In the current state, I'd say no. There may be some BEAST2 packages that allow to do so, but those are not supported yet by `beautier`. With some luck, you can use `beautier` to create the bulk of the XML for a general evolutionary model.

For now, I'd suggest to use BEAST2 directly and one of its packages :+1:

I hope that helps!

**Comment by Spatial-R** [comment]
Thanks! I have finished the analysis using the BEAST.
