### ISSUE TITLE
Make sure NEWS.md is up to date and use release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/beautier#91]
nice work on the new cran release. 

As per our developer guide https://ropensci.github.io/dev_guide/releasing.html#releasing-1 please make sure your NEWS.md has up to date release notes for each CRAN release and use github release notes for each git tagged CRAN release

**Comment by sckott** [comment]
Also, remove this entry `^NEWS\.md$` form your `.Rbuildignore` file - we want the news file to show up on the cran landing page.

**Comment by sckott** [comment]
And the same goes for your other pkgs here, 

thanks !

**Comment by richelbilderbeek** [comment]
AFAICS I did this, also in the packages that depend on beautier.

Thanks :+1:
